[package]
name = "sharedpackage"
version = "0.1.0"
edition = "2021"
crate-type = ["dylib"]

[lib]
name="sharedpackage"
crate-type=["rlib","cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
